name = "MassivelySeparatedFlows"
uuid = "4abfb38b-4535-4480-af0d-a3e8c83bd2d8"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ViscousFlow = "103da179-b3e4-57c1-99a4-586354eb2c5a"

[compat]
Plots = "1.35, 1.36, 1.37, 1.38"
ViscousFlow = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
